describe('E2E test - help', () => {
	it('Open page and go to help', () => {
		browser.url('http://zero.webappsecurity.com/index.html')
		const header = browser.$('#homeMenu')
		header.waitForExist()
		//login
		const signButton = browser.$('#signin_button')
		signButton.waitForExist()
		signButton.click()
		const loginField = browser.$('#user_login')
		loginField.waitForExist()
		loginField.setValue('username')
		const passwordField = browser.$('#user_password')
		passwordField.waitForExist()
		passwordField.setValue('password')
		const signInButton = browser.$('#login_form > div.form-actions > input')
		signInButton.waitForExist()
		signInButton.click()
		expect(browser).toHaveUrl(
			'http://zero.webappsecurity.com/bank/account-summary.html'
		)
		//open help page
		const settingsButton = browser.$('.dropdown-toggle')
		settingsButton.waitForExist()
		settingsButton.click()
		const helpsButton = browser.$('#help_link')
		helpsButton.waitForExist()
		helpsButton.click()
		expect(browser).toHaveUrl('http://zero.webappsecurity.com/help.html')
		const helpTopicsHeader = browser.$('.page-header')
		helpTopicsHeader.waitForExist()
	})
	it('Check help topics', () => {
		const helptitle = browser.$('.span8 > h3')
		helptitle.waitForExist()
		expect(helptitle).toHaveText('How do I log into my account?')
		const transferHelp = browser.$('*=transfer funds?')
		transferHelp.waitForExist()
		transferHelp.click()
		expect(helptitle).toHaveText('How do I transfer funds?')
		const payHelp = browser.$('*=pay bills?')
		payHelp.waitForExist()
		payHelp.click()
		expect(helptitle).toHaveText('How do I pay bills?')
	})
})
