describe('E2E test - Pay', () => {
	it('Open page and login', () => {
		browser.url('http://zero.webappsecurity.com/index.html')
		const signInButton = browser.$('#signin_button')
		signInButton.waitForExist()
		signInButton.click()
		const usernameInputField = browser.$('#user_login')
		usernameInputField.waitForExist()
		usernameInputField.setValue('username')
		const passwordInputField = browser.$('#user_password')
		passwordInputField.waitForExist()
		passwordInputField.setValue('password')
		const loginButton = browser.$('input[type=submit]')
		loginButton.waitForExist()
		loginButton.click()
		const tabToCheck = browser.$('#online_statements_tab')
		tabToCheck.waitForExist()
	})
	it('Should make payment', () => {
		const payBillsButton = browser.$('#pay_bills_tab')
		payBillsButton.waitForExist()
		payBillsButton.click()
		const peyeeSelectbox = browser.$('#sp_payee')
		peyeeSelectbox.waitForExist()
		peyeeSelectbox.selectByAttribute('value', 'bofa')
		const accountSelectbox = browser.$('#sp_account')
		accountSelectbox.waitForExist()
		accountSelectbox.selectByAttribute('value', '5')
		const amountField = browser.$('#sp_amount')
		amountField.waitForExist()
		amountField.setValue('101')
		const dateField = browser.$('#sp_date')
		dateField.waitForExist()
		dateField.setValue('2021-04-19')
		// const dateField = browser.$('#sp_date')
		// dateField.waitForExist()
		// dateField.click()
		// const dayPickerButton = browser.$(
		// 	'#ui-datepicker-div > table > tbody > tr:nth-child(1) > td:nth-child(5) > a'
		// )
		// dayPickerButton.waitForExist()
		// dayPickerButton.click()
		// expect(dateField).toHaveText('2021-04-01')
		const descriptionField = browser.$('#sp_description')
		descriptionField.waitForExist()
        amountField.click()
		descriptionField.setValue('Payment for Han Solo')
		const payButton = browser.$('#pay_saved_payees')
		payButton.waitForExist()
		payButton.click()
	})
	it('Checking if payment was correct', () => {
		const alertPayment = browser.$('#alert_content')
		alertPayment.waitForExist()
		expect(alertPayment).toHaveText('The payment was successfully submitted.')
	})
})
